name: CI

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build project
        run: cargo build --release --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: server
          path: target/release/server

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: client
          path: target/release/client